# Generated by Django 6.1 on 2026-08-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        help_text="Unique identifier for the block (e.g., 'home_intro_title')",
                        max_length=100,
                        unique=True,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ru", models.CharField(blank=True, max_length=255, null=True)),
                ("title_ky", models.CharField(blank=True, max_length=255, null=True)),
                ("title_en", models.CharField(blank=True, max_length=255, null=True)),
                ("content", models.TextField(blank=True, null=True)),
                ("content_ru", models.TextField(blank=True, null=True)),
                ("content_ky", models.TextField(blank=True, null=True)),
                ("content_en", models.TextField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="cms/blocks/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Direction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_ky", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_ky", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="cms/directions/"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("title_ru", models.CharField(max_length=255, null=True)),
                ("title_ky", models.CharField(max_length=255, null=True)),
                ("title_en", models.CharField(max_length=255, null=True)),
                ("slug", models.SlugField(unique=True)),
                ("summary", models.TextField(blank=True, null=True)),
                ("summary_ru", models.TextField(blank=True, null=True)),
                ("summary_ky", models.TextField(blank=True, null=True)),
                ("summary_en", models.TextField(blank=True, null=True)),
                ("content", models.TextField()),
                ("content_ru", models.TextField(null=True)),
                ("content_ky", models.TextField(null=True)),
                ("content_en", models.TextField(null=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="cms/news/"),
                ),
                ("published_date", models.DateTimeField()),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name_plural": "News",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                ("name_ky", models.CharField(max_length=255, null=True)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("description_ru", models.TextField(blank=True, null=True)),
                ("description_ky", models.TextField(blank=True, null=True)),
                ("description_en", models.TextField(blank=True, null=True)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("price_currency", models.CharField(default="KGS", max_length=10)),
                (
                    "direction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="cms.direction",
                    ),
                ),
            ],
            options={
                "ordering": ["direction", "name"],
            },
        ),
    ]
