# Generated by Django 6.1 on 2026-08-20 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('title_ru', models.CharField(max_length=255, null=True)),
                ('title_ky', models.CharField(max_length=255, null=True)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('category', models.CharField(choices=[('general', 'Общее'), ('banquet', 'Банкеты (Айкөл Ордо)'), ('restaurant', 'Ресторан & Гастрономия'), ('chaikhana', 'Чайхана'), ('ethno', 'Этно-село & Юрты'), ('pools', 'Бассейны & Аквазона'), ('spa', 'SPA & Оздоровление'), ('fitness', 'Фитнес-клуб')], default='general', max_length=50)),
                ('image', models.ImageField(upload_to='cms/media_library/')),
                ('description', models.TextField(blank=True, null=True)),
                ('description_ru', models.TextField(blank=True, null=True)),
                ('description_ky', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Медиа-файл',
                'verbose_name_plural': 'Медиабиблиотека',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DirectionGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cms/galleries/')),
                ('title', models.CharField(blank=True, help_text='Подпись / Alt текст', max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, help_text='Подпись / Alt текст', max_length=255, null=True)),
                ('title_ky', models.CharField(blank=True, help_text='Подпись / Alt текст', max_length=255, null=True)),
                ('title_en', models.CharField(blank=True, help_text='Подпись / Alt текст', max_length=255, null=True)),
                ('span', models.CharField(choices=[('normal', 'Обычный (1x1)'), ('wide', 'Широкий (2 колонки)'), ('tall', 'Высокий (2 строки)')], default='normal', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='cms.direction')),
            ],
            options={
                'verbose_name': 'Изображение галереи',
                'verbose_name_plural': 'Галерея направления',
                'ordering': ['direction', 'order'],
            },
        ),
    ]
