# Generated by Django 6.1 on 2026-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_direction_created_at_direction_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_ky', models.TextField(null=True)),
                ('text_en', models.TextField(null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='directiongalleryimage',
            options={'ordering': ['direction', 'order'], 'verbose_name': 'Gallerey image', 'verbose_name_plural': 'Direction gallerey'},
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='content_ky',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='contentblock',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='direction',
            name='name_ru',
        ),
        migrations.RemoveField(
            model_name='directiongalleryimage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='directiongalleryimage',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='directiongalleryimage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='mediaasset',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='summary_ru',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ky',
        ),
        migrations.RemoveField(
            model_name='news',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ky',
        ),
        migrations.RemoveField(
            model_name='service',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ky',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name_ru',
        ),
    ]
