# Generated by Django 6.1 on 2026-08-15 14:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LeadSubmission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "form_type",
                    models.CharField(
                        choices=[
                            ("banquet", "Banquet Booking"),
                            ("restaurant", "Table Reservation"),
                            ("b2b", "B2B Proposal"),
                            ("feedback", "Feedback/Callback"),
                            ("fitness", "Fitness Club"),
                            ("pool", "Swimming Pool"),
                            ("spa", "SPA"),
                            ("ethno", "Ethno-village"),
                        ],
                        max_length=50,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=50)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "payload",
                    models.JSONField(
                        help_text="Stores form-specific fields like event_date, guest_count, etc."
                    ),
                ),
                ("page_url", models.URLField(blank=True, null=True)),
                ("utm_source", models.CharField(blank=True, max_length=255, null=True)),
                ("utm_medium", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "utm_campaign",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "utm_content",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("utm_term", models.CharField(blank=True, max_length=255, null=True)),
                ("consent_given", models.BooleanField(default=True)),
                (
                    "sync_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Sync"),
                            ("success", "Synced Successfully"),
                            ("failed", "Sync Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "bitrix_id",
                    models.CharField(
                        blank=True,
                        help_text="CRM Lead ID once synced",
                        max_length=100,
                        null=True,
                    ),
                ),
                ("sync_errors", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Lead Submission",
                "verbose_name_plural": "Lead Submissions",
                "ordering": ["-created_at"],
            },
        ),
    ]
