# Generated by Django 6.1 on 2026-08-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsubmission',
            name='form_type',
            field=models.CharField(choices=[('contact', 'Contact Form'), ('banquet', 'Banquet Booking'), ('restaurant', 'Table Reservation'), ('b2b', 'B2B Proposal'), ('feedback', 'Feedback/Callback'), ('fitness', 'Fitness Club'), ('pool', 'Swimming Pool'), ('pools', 'Swimming Pools'), ('spa', 'SPA'), ('ethno', 'Ethno-village'), ('chaikhana', 'Chaikhana'), ('events', 'Events'), ('corporate', 'Corporate')], default='contact', max_length=50),
        ),
        migrations.AlterField(
            model_name='leadsubmission',
            name='payload',
            field=models.JSONField(blank=True, default=dict, help_text='Stores form-specific fields like event_date, guest_count, etc.', null=True),
        ),
    ]
